#include "../includes/ServerManager.hpp"

std::string Response::getAutoIndexPage(std::string &content)
{
    std::string page =  "<!DOCTYPE html>\n"
                            "<html lang=\"en\">\n"
                            "<head>\n"
                            "<meta charset=\"UTF-8\">\n"
                            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                            "<title>Webserv</title>\n"
                            "<style>\n"
                            "@import url('https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Orbitron:wght@400..900&family=Poppins:wght@200;400;600;800&family=Sixtyfour&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap');\n"
                            "* {\n"
                            "box-sizing: border-box; margin: 0; padding: 0;\n"
                            "}\n"
                            "html {\n"
                            "width: 100%; height: 100vh; font-family: 'Work Sans', sans-serif;\n"
                            "}\n"
                            "body {\n"
                            "width: 100%; padding: 20px; padding-bottom: 100px; height: 100%; display: flex; background-color: #202c3c; \n"
                            "}\n"
                            ".container {\n"
                            "display: flex; padding-left: 50px; flex-direction: column; width: 100%; margin: 20px; margin-bottom: 40px; padding: 20px; height: auto;\n"
                            "}\n"
                            "a {\n"
                            "color: white; font-size: 16px; font-weight: 500; text-decoration: none; width: 100%; padding: 15px; \n"
                            " border-radius: 8px; transition: transform 0.2s ease-in-out;}\n"
                            "ul {\n"
                            "list-style: none; display: flex; flex-direction: column;\n"
                            "}\n"
                            "li {\n"
                            "height: 50px; display: flex; color: white; align-items: center;\n"
                            "}\n"
                            "#title {\n"
                            "padding: 0; font-size: 26px; font-weight: bold; margin-bottom: 20px; color: rgb(228, 61, 0);\n"
                            "}\n"
                            "a:hover {\n"
                            "background-color: rgb(228, 61, 0); cursor: pointer;\n"
                            ";transform: translateX(20px);}\n"
                            "</style>\n"
                            "</head>\n"
                            "<body>\n"
                            "<div class=\"container\">\n"
                            "<div class=\"content\">\n"
                            "<ul>\n"
                            "<p id=\"title\">Path: " + this->serverPath + "</p>\n" + content +
                            "</ul>\n"
                            "</div>\n"
                            "</div>\n"
                            "</body>\n"
                            "</html>"; 
    return page;
}